### ISSUE TITLE
Can't read property of undefined in data.size.width

### ISSUE THREAD

**Issue by Geffreyvanderbos** [AlainGourves/shairport-metadata-display#2]
Alain! 

Thank you so much for the exciting code.

I can't seem to get it to work. It's struggling with 

```
/home/pi/shairport-metadata-display/app.js:352
                const w = data.size.width;
                                    ^

TypeError: Cannot read properties of undefined (reading 'width')
```

Is there anything I can do to fix it on my side?

**Comment by Geffreyvanderbos** [comment]
Installing Graphicsmagick did the trick. ;)

sudo apt-get install graphicsmagick

**Comment by AlainGourves** [comment]
Sorry to be late !
I've update the README file to stress the ImageMagick requirement.
You should maybe replace GraphicsMagick with ImageMagick or install it in parallel: `gm` works with both but `imagecolors` requires only ImageMagick for color palettes  extraction.
Anyway, thanks for your feedback.
